version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase about zaplacrecepte ...
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - cp target/zaplacrecepte-0.0.1.jar ../
      - echo Build completed on `date`
artifacts:
  files:
    - target/zaplacrecepte-0.0.1.jar
    - zaplacrecepte-0.0.1.jar