p24:
  host: "https://secure.przelewy24.pl"
  clientId: 118607
  crc: "6cbf3f18bf0aba5b"
  apiKey: "ac64e455852ab6bc50fe54d1ed4baa93"
  notifyUrl: "https://api.zaplacrecepte.pl/payment/notification/p24/"
  continueUrl: "https://www.zaplacrecepte.pl/thankyou"
  shortPaymentLink: "https://www.zaplacrecepte.pl/r/"
  splitPaymentUrl: "https://secure.przelewy24.pl/external/118607.php"

security:
  login: drkrzystyniak
  password: jankes