spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://database-zaplacrecepte-notencrypted.cknwhegghgoz.eu-west-2.rds.amazonaws.com:3306/zaplacrecepte_prod
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 10000
      poolName: HikariPool
      jdbcUrl: jdbc:mysql://database-zaplacrecepte-notencrypted.cknwhegghgoz.eu-west-2.rds.amazonaws.com:3306/zaplacrecepte_prod
      username: user_prod
      password: ${DB_PASSWORD}
      driverClassName: com.mysql.cj.jdbc.Driver

payment:
  prescriptionBasedShortPaymentLink: "https://www.zaplacrecepte.pl/p/"
  serviceBasedShortPaymentLink: "https://www.zaplacrecepte.pl/s/"
  p24:
    host: "https://secure.przelewy24.pl"
    clientId: 118607
    crc: "6cbf3f18bf0aba5b"
    apiKey: "ac64e455852ab6bc50fe54d1ed4baa93"
    notifyUrl: "https://api.zaplacrecepte.pl/payment/notification/p24/"
    prescriptionBasedContinueUrl: "https://www.zaplacrecepte.pl/prescription/thankyou"
    serviceBasedContinueUrl: "https://www.zaplacrecepte.pl/service/thankyou"
    splitPaymentUrl: "https://secure.przelewy24.pl/external/118607.php"
  bm:
    startTransactionUrl: "https://pay.bm.pl/payment"
    sharedKey: "51473d84c2c6e0294a6f05457c6e1f13dedf6f68"
    serviceId: 102652

paymentReminder:
  cronExpression: 0 30 15 ? * *