spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://database-zaplacrecepte-notencrypted.cknwhegghgoz.eu-west-2.rds.amazonaws.com:3306/zaplacrecepte_demo
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 10000
      poolName: HikariPool
      jdbcUrl: jdbc:mysql://database-zaplacrecepte-notencrypted.cknwhegghgoz.eu-west-2.rds.amazonaws.com:3306/zaplacrecepte_demo
      username: user_demo
      password: ${DB_PASSWORD}
      driverClassName: com.mysql.cj.jdbc.Driver

p24:
  host: "https://sandbox.przelewy24.pl"
  clientId: 118607
  crc: "373004a537f5c0f9"
  apiKey: "3c233647d304fa4ee9b7cf1c76529a99"
  notifyUrl: "https://api.demo.zaplacrecepte.pl/payment/notification/p24/"
  continueUrl: "https://demo.zaplacrecepte.pl/thankyou"
  shortPaymentLink: "https://demo.zaplacrecepte.pl/r/"

paymentReminder:
  cronExpression: 0 30 15 ? * *