server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

p24:
  host: "https://sandbox.przelewy24.pl"
  clientId: 118607
  crc: "373004a537f5c0f9"
  apiKey: "3c233647d304fa4ee9b7cf1c76529a99"
  notifyUrl: "https://api.demo.zaplacrecepte.pl/payment/notification/p24/"
  prescriptionBasedContinueUrl: "https://demo.zaplacrecepte.pl/prescription/thankyou"
  serviceBasedContinueUrl: "https://demo.zaplacrecepte.pl/service/thankyou"
  prescriptionBasedShortPaymentLink: "https://demo.zaplacrecepte.pl/p/"
  serviceBasedShortPaymentLink: "https://demo.zaplacrecepte.pl/s/"

paymentReminder:
  cronExpression: 0 30 15 ? * *