package com.hastlin.zaplacrecepte.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.List;

@DynamoDBTable(tableName = "PRESCRIPTION")
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Setter
@ToString
public class PrescriptionEntity {


    private String id;

    private String firstName;
    private String lastName;
    private String pesel;
    private String postalCode;
    private String remarks;
    private String phoneNumber;
    private String email;
    private String status;
    private String createDateTime;
    private String orderId;
    private String paymentToken;
    private String orderRedirectFromKey;
    private String orderRedirectToUrl;
    private String prescriptionNumber;
    private List<String> errors;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getPesel() {
        return pesel;
    }

    @DynamoDBAttribute
    public String getPostalCode() {
        return postalCode;
    }

    @DynamoDBAttribute
    public String getRemarks() {
        return remarks;
    }

    @DynamoDBAttribute
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public String getCreateDateTime() {
        return createDateTime;
    }

    @DynamoDBAttribute
    public String getOrderId() {
        return orderId;
    }

    @DynamoDBAttribute
    public String getPaymentToken() {
        return paymentToken;
    }

    @DynamoDBAttribute
    public String getOrderRedirectFromKey() {
        return orderRedirectFromKey;
    }

    @DynamoDBAttribute
    public String getOrderRedirectToUrl() {
        return orderRedirectToUrl;
    }

    @DynamoDBAttribute
    public String getPrescriptionNumber() {
        return prescriptionNumber;
    }

    @DynamoDBAttribute
    public List getErrors() {
        return errors;
    }

    public void addError(String newError) {
        this.errors.add(newError);
    }
}
