package com.hastlin.zaplacrecepte.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@DynamoDBTable(tableName = "PRESCRIPTION")
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Setter
@ToString
public class PrescriptionEntity {


    private String id;

    private String firstName;
    private String lastName;
    private String pesel;
    private String postalCode;
    private String remarks;
    private String phoneNumber;
    private String email;
    private String status;
    private String createDateTime;
    private String orderId;
    private String paymentToken;
    private String orderUrl;
    private String prescriptionNumber;

    @DynamoDBTypeConvertedJson
    private List<String> errors;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getPesel() {
        return pesel;
    }

    @DynamoDBAttribute
    public String getPostalCode() {
        return postalCode;
    }

    @DynamoDBAttribute
    public String getRemarks() {
        return remarks;
    }

    @DynamoDBAttribute
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public String getCreateDateTime() {
        return createDateTime;
    }

    @DynamoDBAttribute
    public String getOrderId() {
        return orderId;
    }

    @DynamoDBAttribute
    public String getPaymentToken() {
        return paymentToken;
    }

    @DynamoDBAttribute
    public String getOrderUrl() {
        return orderUrl;
    }

    @DynamoDBAttribute
    public String getPrescriptionNumber() {
        return prescriptionNumber;
    }

    @DynamoDBAttribute(attributeName = "errors")
    public List<String> getErrors() {
        return errors;
    }

    public void addError(String newError) {
        if(Objects.isNull(errors)){
            errors = new ArrayList<>();
        }
        this.errors.add(newError);
    }
}
