ALTER TABLE `zaplacrecepte_test`.`USER`
    ADD COLUMN `ACCOUNT_NUMBER` VARCHAR(64);
ALTER TABLE `zaplacrecepte_demo`.`USER`
    ADD COLUMN `ACCOUNT_NUMBER` VARCHAR(64);
ALTER TABLE `zaplacrecepte_prod`.`USER`
    ADD COLUMN `ACCOUNT_NUMBER` VARCHAR(64);

ALTER TABLE `zaplacrecepte_test`.`USER`
    ADD COLUMN `ACCOUNT_OWNER` VARCHAR(35);
ALTER TABLE `zaplacrecepte_demo`.`USER`
    ADD COLUMN `ACCOUNT_OWNER` VARCHAR(35);
ALTER TABLE `zaplacrecepte_prod`.`USER`
    ADD COLUMN `ACCOUNT_OWNER` VARCHAR(35);

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION`
    ADD COLUMN `ORDER_URL_TMP` VARCHAR(1000);
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION`
    ADD COLUMN `ORDER_URL_TMP` VARCHAR(1000);
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION`
    ADD COLUMN `ORDER_URL_TMP` VARCHAR(1000);

UPDATE `zaplacrecepte_test`.`PRESCRIPTION`
SET ORDER_URL_TMP=ORDER_URL;
UPDATE `zaplacrecepte_demo`.`PRESCRIPTION`
SET ORDER_URL_TMP=ORDER_URL;
UPDATE `zaplacrecepte_prod`.`PRESCRIPTION`
SET ORDER_URL_TMP=ORDER_URL;

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION`
    DROP COLUMN `ORDER_URL`;
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION`
    DROP COLUMN `ORDER_URL`;
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION`
    DROP COLUMN `ORDER_URL`;

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION` RENAME COLUMN ORDER_URL_TMP TO ORDER_URL;
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION` RENAME COLUMN ORDER_URL_TMP TO ORDER_URL;
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION` RENAME COLUMN ORDER_URL_TMP TO ORDER_URL;