ALTER TABLE `zaplacrecepte_test`.`USER`
    ADD COLUMN `PAYMENT_PROVIDER` VARCHAR(30);

ALTER TABLE `zaplacrecepte_demo`.`USER`
    ADD COLUMN `PAYMENT_PROVIDER` VARCHAR(30);

ALTER TABLE `zaplacrecepte_prod`.`USER`
    ADD COLUMN `PAYMENT_PROVIDER` VARCHAR(30);