ALTER TABLE `zaplacrecepte_test`.`USER`
    ADD COLUMN `CLIENT_TYPE` VARCHAR(64);
ALTER TABLE `zaplacrecepte_demo`.`USER`
    ADD COLUMN `CLIENT_TYPE` VARCHAR(64);
ALTER TABLE `zaplacrecepte_prod`.`USER`
    ADD COLUMN `CLIENT_TYPE` VARCHAR(64);

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION`
    ADD COLUMN `ORDER_ID_STRING` VARCHAR(64);
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION`
    ADD COLUMN `ORDER_ID_STRING` VARCHAR(64);
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION`
    ADD COLUMN `ORDER_ID_STRING` VARCHAR(64);

UPDATE `zaplacrecepte_test`.`PRESCRIPTION`
SET ORDER_ID_STRING=CONVERT(ORDER_ID, char);
UPDATE `zaplacrecepte_demo`.`PRESCRIPTION`
SET ORDER_ID_STRING=CONVERT(ORDER_ID, char);
UPDATE `zaplacrecepte_prod`.`PRESCRIPTION`
SET ORDER_ID_STRING=CONVERT(ORDER_ID, char);

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION`
    DROP COLUMN `ORDER_ID`;
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION`
    DROP COLUMN `ORDER_ID`;
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION`
    DROP COLUMN `ORDER_ID`;

ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION` RENAME COLUMN ORDER_ID_STRING TO ORDER_ID;
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION` RENAME COLUMN ORDER_ID_STRING TO ORDER_ID;
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION` RENAME COLUMN ORDER_ID_STRING TO ORDER_ID;



ALTER TABLE `zaplacrecepte_test`.`PRESCRIPTION`
    ADD COLUMN `PRICE` INTEGER;
ALTER TABLE `zaplacrecepte_demo`.`PRESCRIPTION`
    ADD COLUMN `PRICE` INTEGER;
ALTER TABLE `zaplacrecepte_prod`.`PRESCRIPTION`
    ADD COLUMN `PRICE` INTEGER;

UPDATE `zaplacrecepte_test`.`PRESCRIPTION`
SET PRICE=30;
UPDATE `zaplacrecepte_demo`.`PRESCRIPTION`
SET PRICE=30;
UPDATE `zaplacrecepte_prod`.`PRESCRIPTION`
SET PRICE=30;

ALTER TABLE `zaplacrecepte_test`.`USER`
    ADD COLUMN `DEFAULT_PRICE` INTEGER;
ALTER TABLE `zaplacrecepte_demo`.`USER`
    ADD COLUMN `DEFAULT_PRICE` INTEGER;
ALTER TABLE `zaplacrecepte_prod`.`USER`
    ADD COLUMN `DEFAULT_PRICE` INTEGER;